// Generated by jextract

package org.golang;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef _GoString_ GoString
 * }
 */
public class GoString extends _GoString_ {

    GoString() {
        // Should not be called directly
    }
}

