// Generated by jextract

package org.golang;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class libhello_h extends libhello_h$shared {

    libhello_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("hello"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());

    /**
     * {@snippet lang=c :
     * typedef long ptrdiff_t
     * }
     */
    public static final OfLong ptrdiff_t = libhello_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long size_t
     * }
     */
    public static final OfLong size_t = libhello_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef int wchar_t
     * }
     */
    public static final OfInt wchar_t = libhello_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef signed char GoInt8
     * }
     */
    public static final OfByte GoInt8 = libhello_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef unsigned char GoUint8
     * }
     */
    public static final OfByte GoUint8 = libhello_h.C_CHAR;
    /**
     * {@snippet lang=c :
     * typedef short GoInt16
     * }
     */
    public static final OfShort GoInt16 = libhello_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef unsigned short GoUint16
     * }
     */
    public static final OfShort GoUint16 = libhello_h.C_SHORT;
    /**
     * {@snippet lang=c :
     * typedef int GoInt32
     * }
     */
    public static final OfInt GoInt32 = libhello_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef unsigned int GoUint32
     * }
     */
    public static final OfInt GoUint32 = libhello_h.C_INT;
    /**
     * {@snippet lang=c :
     * typedef long long GoInt64
     * }
     */
    public static final OfLong GoInt64 = libhello_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef unsigned long long GoUint64
     * }
     */
    public static final OfLong GoUint64 = libhello_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef GoInt64 GoInt
     * }
     */
    public static final OfLong GoInt = libhello_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef GoUint64 GoUint
     * }
     */
    public static final OfLong GoUint = libhello_h.C_LONG_LONG;
    /**
     * {@snippet lang=c :
     * typedef size_t GoUintptr
     * }
     */
    public static final OfLong GoUintptr = libhello_h.C_LONG;
    /**
     * {@snippet lang=c :
     * typedef float GoFloat32
     * }
     */
    public static final OfFloat GoFloat32 = libhello_h.C_FLOAT;
    /**
     * {@snippet lang=c :
     * typedef double GoFloat64
     * }
     */
    public static final OfDouble GoFloat64 = libhello_h.C_DOUBLE;
    /**
     * {@snippet lang=c :
     * typedef void *GoMap
     * }
     */
    public static final AddressLayout GoMap = libhello_h.C_POINTER;
    /**
     * {@snippet lang=c :
     * typedef void *GoChan
     * }
     */
    public static final AddressLayout GoChan = libhello_h.C_POINTER;

    private static class Add {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            libhello_h.C_LONG_LONG,
            libhello_h.C_LONG_LONG,
            libhello_h.C_LONG_LONG
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("Add");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern GoInt Add(GoInt x, GoInt y)
     * }
     */
    public static FunctionDescriptor Add$descriptor() {
        return Add.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern GoInt Add(GoInt x, GoInt y)
     * }
     */
    public static MethodHandle Add$handle() {
        return Add.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern GoInt Add(GoInt x, GoInt y)
     * }
     */
    public static MemorySegment Add$address() {
        return Add.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern GoInt Add(GoInt x, GoInt y)
     * }
     */
    public static long Add(long x, long y) {
        var mh$ = Add.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("Add", x, y);
            }
            return (long)mh$.invokeExact(x, y);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final MemorySegment NULL = MemorySegment.ofAddress(0L);
    /**
     * {@snippet lang=c :
     * #define NULL (void*) 0
     * }
     */
    public static MemorySegment NULL() {
        return NULL;
    }
}

