// Generated by jextract

package org.hello;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class helloworld_h extends helloworld_h$shared {

    helloworld_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.libraryLookup(System.mapLibraryName("helloworld"), LIBRARY_ARENA)
            .or(SymbolLookup.loaderLookup())
            .or(Linker.nativeLinker().defaultLookup());


    private static class helloworld {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("helloworld");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * extern void helloworld()
     * }
     */
    public static FunctionDescriptor helloworld$descriptor() {
        return helloworld.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * extern void helloworld()
     * }
     */
    public static MethodHandle helloworld$handle() {
        return helloworld.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * extern void helloworld()
     * }
     */
    public static MemorySegment helloworld$address() {
        return helloworld.ADDR;
    }

    /**
     * {@snippet lang=c :
     * extern void helloworld()
     * }
     */
    public static void helloworld() {
        var mh$ = helloworld.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("helloworld");
            }
            mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

